alias tm 'tmux'
alias ll 'exa -algh --git'
alias ls 'exa'
alias sl 'exa'
alias s 'exa'
alias git 'hub'
alias vim 'nvim'
alias cs 'colorme-ssh'
alias openssl '/usr/local/Cellar/openssl/1.0.2l/bin/openssl'
